### ISSUE TITLE
RELEASE 0.0.3: Refactor

### ISSUE THREAD

**Issue by ZetrextJG** [mini-pw/PvSTATEM#63]
Jakub:
- [x] Finish writing those two functions
- [x] Layout file reading #64
- [x] Encapsulate model (and move the implementation) #76 #41 #27
- [x] Integrate the new parser with the feat/refactor code #67 #25 
- [x] Single function to load the data to a Plate #67 

Mateusz:
- [ ] #111
- [x] Move the translation of the sample names to sample types implementation #66 
- [x] Update documentation (New vignettes)

Tymek:
- [x] Fix model charts #72
- [x] Rewrite validation #73
- [x] #74 

If there is time:
- [x] Blank adjustment #68 
- [x] Bead count plots #71 
- [x] Sample MFI boxplot++ #69 #48

**Comment by Fersoil** [comment]
almost all tasks from this issue have been completed, the plot factory might be transfered to the future release, since this feature is not crucial. 

The additional implemented features are more than enough to successfully release a new package version.
